#!/usr/bin/env python3
"""Generate a self-contained UTF-16 longest-match table for Wine usp10.

Input data is Unicode Emoji 15.1's public emoji-sequences.txt and
emoji-zwj-sequences.txt (Unicode License v3).  The generated header has no
local paths and includes the source SHA-256 values in its comment.
"""
from hashlib import sha256
import argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent
parser = argparse.ArgumentParser(description='Generate the Wine RGI emoji matcher header.')
parser.add_argument('--unicode-dir', type=Path, default=HERE / 'unicode-15.1')
parser.add_argument('--output', type=Path, required=True)
args = parser.parse_args()
DATA = args.unicode_dir
OUT = args.output
NAMES = ('emoji-sequences.txt', 'emoji-zwj-sequences.txt')

def read_sequences():
    seen, result = set(), []
    for name in NAMES:
        for line in (DATA / name).read_text(encoding='utf-8').splitlines():
            body = line.split('#', 1)[0].strip()
            if not body or ';' not in body:
                continue
            points, kind = (part.strip() for part in body.split(';', 1))
            if not (kind.startswith('RGI_') or kind.startswith('Emoji_Keycap_Sequence')) or '..' in points:
                continue
            seq = tuple(int(point, 16) for point in points.split())
            if seq not in seen:
                seen.add(seq)
                result.append(seq)
    # Wine may consume VS16 during initial glyph mapping.  Preserve the exact
    # surrounding RGI components in a second matching form.
    for seq in tuple(result):
        no_vs16 = tuple(point for point in seq if point != 0xfe0f)
        if no_vs16 != seq and no_vs16 not in seen:
            seen.add(no_vs16)
            result.append(no_vs16)
    return result

def utf16(seq):
    words = []
    for point in seq:
        if point <= 0xffff:
            words.append(point)
        else:
            point -= 0x10000
            words.extend((0xd800 + (point >> 10), 0xdc00 + (point & 0x3ff)))
    return tuple(words)

sequences = []
for seq in read_sequences():
    words = utf16(seq)
    sequences.append((seq[0], words))

# Longest first makes prefix families deterministic; scalar sort enables a
# binary-search bucket lookup, so an ordinary D83D high surrogate is not a
# linear scan of every emoji sequence.
sequences.sort(key=lambda row: (row[0], -len(row[1]), row[1]))
data, entries = [], []
for first, words in sequences:
    offset = len(data)
    data.extend(words)
    entries.append((first, offset, len(words)))

hashes = {name: sha256((DATA / name).read_bytes()).hexdigest() for name in NAMES}
lines = [
    '/* Generated by generate_emoji_rgi_header.py.  Do not edit.\n',
    ' * Source: Unicode Emoji 15.1 emoji-sequences.txt and emoji-zwj-sequences.txt\n',
    ' * License: Unicode License v3 <https://www.unicode.org/license.txt>\n',
    *(f' * {name} SHA-256: {hashes[name]}\n' for name in NAMES),
    ' */\n',
    '#ifndef __WINE_USP10_EMOJI_RGI_SEQUENCES_H\n',
    '#define __WINE_USP10_EMOJI_RGI_SEQUENCES_H\n\n',
    'struct emoji_rgi_sequence { unsigned int first, offset; unsigned short length; };\n\n',
    'static const WCHAR emoji_rgi_data[] = {\n',
]
for index in range(0, len(data), 12):
    lines.append('    ' + ', '.join(f'0x{word:04x}' for word in data[index:index + 12]) + ',\n')
lines.extend(['};\n\n', 'static const struct emoji_rgi_sequence emoji_rgi_sequences[] = {\n'])
for first, offset, length in entries:
    lines.append(f'    {{ 0x{first:06x}, {offset}, {length} }},\n')
lines.extend([
    '};\n\n',
    'static inline unsigned int emoji_rgi_first_scalar(const WCHAR *text, int count)\n',
    '{\n',
    '    if (count > 1 && text[0] >= 0xd800 && text[0] <= 0xdbff &&\n',
    '        text[1] >= 0xdc00 && text[1] <= 0xdfff)\n',
    '        return 0x10000 + ((text[0] - 0xd800) << 10) + text[1] - 0xdc00;\n',
    '    return text[0];\n',
    '}\n\n',
    'static inline int emoji_rgi_match_utf16(const WCHAR *text, int count)\n',
    '{\n',
    '    unsigned int first, lo = 0, hi = ARRAY_SIZE(emoji_rgi_sequences), mid, j;\n',
    '    if (count < 2) return 0;\n',
    '    first = emoji_rgi_first_scalar(text, count);\n',
    '    while (lo < hi)\n',
    '    {\n',
    '        mid = lo + (hi - lo) / 2;\n',
    '        if (emoji_rgi_sequences[mid].first < first) lo = mid + 1; else hi = mid;\n',
    '    }\n',
    '    while (lo < ARRAY_SIZE(emoji_rgi_sequences) && emoji_rgi_sequences[lo].first == first)\n',
    '    {\n',
    '        const struct emoji_rgi_sequence *seq = &emoji_rgi_sequences[lo++];\n',
    '        if (seq->length > count) continue;\n',
    '        for (j = 0; j < seq->length; ++j) if (text[j] != emoji_rgi_data[seq->offset + j]) break;\n',
    '        if (j == seq->length) return seq->length;\n',
    '    }\n',
    '    return 0;\n',
    '}\n\n',
    '#endif\n',
])
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(''.join(lines), encoding='utf-8')
print(f'output={OUT} sequences={len(entries)} words={len(data)}')
